import { Montserrat } from "next/font/google";
import "./globals.sass";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400","500", "600", "700", "800"], 
  variable: "--font-montserrat", 
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        {children}
      </body>
    </html>
  );
}
